import Head from 'next/head';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
      </Head>
      <Header />
      <div className="mx-auto max-w-6xl px-4 py-8 text-white">
        <article className="prose prose-invert lg:prose-xl">
          <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
          <p className="text-gray-300">Last updated: March 17, 2023</p>
          
          <div className="space-y-6 mt-8">
            <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          </div>

          <div className="mt-12">
            <h2 className="text-2xl font-bold mb-6">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold mb-4">Interpretation</h3>
            <p className="mb-6">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <h3 className="text-xl font-semibold mb-4">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Your Company.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing details of Your browsing history on that website among its many uses.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            </ul>
          </div>

          <div className="mt-12">
            <h2 className="text-2xl font-bold mb-6">Collection and Use of Your Personal Data</h2>
            <h3 className="text-xl font-semibold mb-4">Types of Data Collected</h3>
            <p className="mb-4"><strong>Personal Data</strong></p>
            <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>
            
            <h3 className="text-xl font-semibold mb-4">Use of Your Personal Data</h3>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              {/* Add more purposes as needed */}
            </ul>
            <p className="mb-4">We may share Your personal information in certain situations as described in the policy.</p>
          </div>

          <div className="mt-12">
            <h2 className="text-2xl font-bold mb-6">Changes to this Privacy Policy</h2>
            <p className="mb-4">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this
            Privacy Policy are effective when they are posted on this page.</p>
          </div>
        </article>
      </div>
      <Footer />
    </>
  )
}